In [1]:
# Import modules
import logging
#!pip install wikipedia-api
import wikipediaapi
import databasesaver as dbs
import requests
import pandas as pd
import os
import re

notebook_path = os.getcwd()
print(notebook_path)

/Anton1G3/Study/ds23_f-rdjupad_python/lektion_5


# Explode styles and insribers

In [2]:
df = pd.read_csv('Uppland.csv')
#df.loc[1080]
# convert to w2v+explode
# X, y train -> predict
#df["Inscriber"] = df["Inscriber"].fillna(0)
df["Inscriber"] = df["Inscriber"].str.split(r"\s*,\s*", regex=True)
x = df.explode("Inscriber")
df["Stil"] = df["Stil"].str.split(r"\s*,\s*", regex=True)
y = df.explode("Stil")
df_out = (
    pd.concat(
             [df.set_index("signum"), pd.crosstab(x["signum"], x["Inscriber"]), pd.crosstab(y["signum"], y["Stil"])], axis=1
    )
    .reset_index()
    .drop(columns=["Inscriber","Stil"])
)

#result = df[df['Period_end'] - df['Period_begin'] < 31]


#mask = df['Inscriber'].str.contains(r'Tidkume', na=False) #Öpir
#result = df[mask]

df_out = df_out.fillna(0)


In [3]:
# cut runic text i words
#! pip install text-preprocessing
from text_preprocessing import preprocess_text
df_out['translitterering'] = df_out['translitterering'].str.replace('(','')
df_out['translitterering'] = df_out['translitterering'].str.replace(')','')
df_out['translitterering'] = df_out['translitterering'].str.replace('[','')
df_out['translitterering'] = df_out['translitterering'].str.replace(']','')
df_out['translitterering'] = df_out['translitterering'].str.replace('...','')
df_out['translitterering'] = df_out['translitterering'].str.replace(r"\s*×\s*",' ', regex=True)
df_out['translitterering'] = df_out['translitterering'].str.replace(r"\s*\+\s*",' ', regex=True)
df_out['translitterering'] = df_out['translitterering'].str.replace(r"\s*:\s*",' ', regex=True)
df_out['translitterering'] = df_out['translitterering'].str.replace(r"\s*\|\s*",' ', regex=True)
df_out['translitterering'] = df_out['translitterering'].str.replace(r"\s*·\s*",' ', regex=True)
#df_out['translitterering'] = df_out['translitterering'].str.replace(r"\s*-\s*",'', regex=True)
df_out['translitterering'] = df_out['translitterering'].str.replace(r"\s*\.\s*",' ', regex=True)
#df_out['translitterering'] = df_out['translitterering'].str.replace(r"\s*,\s*",' ', regex=True)
df_out['translitterering'] = df_out['translitterering'].str.split()

[nltk_data] Downloading package omw-1.4 to /Users/angr/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [4]:
# get Word2Vec model
#! pip install gensim
from gensim.models import Word2Vec
Word2Vec_model = Word2Vec(df_out['translitterering'], seed=0, workers=4, sg=0)

In [19]:
# one can really have fun with Word2Vec
print(Word2Vec_model.wv.most_similar(positive=['stain'], topn=10))
Word2Vec_model.wv['stain']


[('auk', 0.9995619058609009), ('at', 0.9994423389434814), ('sin', 0.9994022250175476), ('stan', 0.9993938207626343), ('stin', 0.9993863701820374), ('bru', 0.9993818998336792), ('a', 0.9993786811828613), ('sun', 0.9993732571601868), ('litu', 0.9993696212768555), ('til', 0.9993618726730347)]


array([ 0.01990198, -0.26984367, -0.09364644, -0.20273563,  0.32198715,
        0.1808871 , -0.06890657, -0.4660922 ,  0.15171771,  0.15936662,
        0.22665024, -0.00474732,  0.28223267,  0.40189868,  0.22359802,
        0.02365612,  0.09475268, -0.25985155, -0.24575746,  0.24890137,
        0.01919118,  0.38667792, -0.11874455, -0.3156656 ,  0.32295287,
        0.3154996 , -0.00605468,  0.22887686, -0.02790035, -0.07519761,
        0.16482653, -0.04385997,  0.15106302, -0.02699993, -0.42167392,
       -0.02338125,  0.14386305, -0.18373626, -0.0182999 ,  0.23182428,
       -0.139318  , -0.43253285, -0.07465581, -0.03682341, -0.14694676,
       -0.24436319, -0.23346896,  0.01663892, -0.11757983,  0.06113906,
       -0.29901743,  0.09211636, -0.18759353,  0.5586597 ,  0.04270501,
       -0.5612425 , -0.04418324,  0.25162834, -0.13355294,  0.2178231 ,
        0.04830896,  0.32130057,  0.06848127, -0.31652805,  0.66563857,
       -0.08511582, -0.22482121,  0.07546633,  0.13712865,  0.08

In [20]:
Word2Vec_model = Word2Vec.load("word2vec.model")
print(Word2Vec_model.wv.most_similar(positive=['stain'], topn=10))
Word2Vec_model.wv['stain']


[('auk', 0.9995585083961487), ('at', 0.9994363784790039), ('sin', 0.9993960857391357), ('stin', 0.9993941187858582), ('bru', 0.9993917346000671), ('stan', 0.9993906617164612), ('litu', 0.9993825554847717), ('a', 0.9993726015090942), ('sun', 0.9993721842765808), ('til', 0.9993554949760437)]


array([ 0.04138811, -0.21391557, -0.02111843, -0.3143679 ,  0.2787874 ,
        0.07077538, -0.12365589, -0.48742977,  0.10130572,  0.1880094 ,
        0.2405688 ,  0.10236811,  0.25534266,  0.4280772 ,  0.31930357,
       -0.0089304 ,  0.02272191, -0.3031695 , -0.31360686,  0.20200346,
        0.0031526 ,  0.37713996, -0.03469337, -0.3363603 ,  0.25294045,
        0.23694251,  0.11561681,  0.13001245, -0.01674494, -0.10666823,
        0.17235565, -0.08809467,  0.14213423, -0.00658507, -0.43731752,
       -0.04672825,  0.09348158, -0.17608614, -0.00113934,  0.26653934,
       -0.03452369, -0.3974576 , -0.12508468, -0.06816301, -0.21105656,
       -0.18912204, -0.2474511 ,  0.04166899, -0.16986448,  0.17722233,
       -0.24612933,  0.0591435 , -0.20149206,  0.60305077,  0.03879384,
       -0.36921036, -0.10691167,  0.18350992, -0.11931608,  0.21193273,
       -0.02150366,  0.39401188, -0.06437674, -0.3128894 ,  0.6233673 ,
       -0.04372983, -0.21970865,  0.12050993,  0.15459123,  0.11

In [21]:

# we have vectorzed words, now we need to vectorize sentences

import numpy as np
# Creating empty dataframe to hold sentences
W2Vec_data=pd.DataFrame()
    
# Looping through each row for the data
#count = 0
for sentence in df_out['translitterering']:
    #count = count + 1
    #if count > 4 : break
    #print(sentence)
# initiating a sentence with all zeros
    vec_sentence = np.zeros(100)

# Looping thru each word in the sentence and if its present in 
# the Word2Vec model then storing its vector
    for word in sentence:
        #print(word)
        if word in Word2Vec_model.wv.key_to_index.keys() :
            vec_sentence=vec_sentence+Word2Vec_model.wv[word]
        # Appending the sentence to the dataframe
    W2Vec_data=pd.concat([W2Vec_data,pd.DataFrame([vec_sentence])],ignore_index=True)
#return(W2Vec_Data)

In [22]:
#create train data

df_ML = pd.concat([W2Vec_data, df_out], axis=1)
df_ML = df_ML.drop(columns=["signum","revisionID","translitterering","normalisering","translation","Material","edition"])
X = df_ML[df_ML['Period_end'] - df_ML['Period_begin'] < 31]
y = (np.array(X['Period_end']) + np.array(X['Period_begin']))/2


begin_period = [1043 - 8.5, (1097 + 1108)/2 - 5, 1085 - 14, 1050 - 5, 1066 - 9.5, 1085 - 5]
end_period = [1043 + 8.5, (1097 + 1108)/2 + 5, 1085 + 14, 1050 + 5, 1066 + 9.5, 1085 + 5]

count = 0
for insk in ["Upplands runinskrifter 35", "Upplands runinskrifter 209", "Orkestastenen", "Upplands runinskrifter 644", "Upplands runinskrifter 11", "Upplands runinskrifter 229"] :
    X = pd.concat([X,df_ML.loc[df_out['signum'] == insk]],ignore_index=True)
    X.at[len(X)-1, 'Period_begin'] = begin_period[count]
    X.at[len(X)-1, 'Period_end'] = end_period[count]
    y = np.append( y, (begin_period[count] + end_period[count])/2 )
    count = count + 1
        #if df.loc[df['signum'] == inskrift, 'revisionID'].item() < page_data['parse']['revid']:
X = X.fillna(0)


In [23]:
# train the model
from sklearn.neighbors import KNeighborsRegressor
X.columns = X.columns.astype(str)
neigh = KNeighborsRegressor(n_neighbors=5)
neigh.fit(X, y)


KNeighborsRegressor()

In [27]:
import pickle 
     
# load the model from disk
neigh = pickle.load(open('KNeighborsRegressor_pickle_file', 'rb'))
#result = neigh.predict(X_test) 

In [28]:
# test on iscribers like Tidkume (person, see pdf) and Öpir (verksamhet)
count = 0
mask = df['Inscriber'].str.contains('Tidkume', na=False, regex=False) #Öpir Tidkume
#print(df[mask])

#X_pred = df_ML["Öpir" in df["Inscriber"]]
X_pred = df_ML[mask]
X_pred = X_pred.fillna(0)
X_pred.columns = X_pred.columns.astype(str)
print(neigh.predict(X_pred))
#coordinates are available in 
df[mask]


[1057.  1029.5 1029.5 1029.5 1029.5 1029.5 1029.5 1029.5 1029.5 1029.5
 1029.5 1029.5 1029.5 1029.5 1029.5]


signum  revisionID  \
606          Upplands runinskrifter 691    54589581   
622          Upplands runinskrifter 718    54593741   
635          Upplands runinskrifter 733    54537884   
644          Upplands runinskrifter 742    54631331   
657          Upplands runinskrifter 758    51521048   
658          Upplands runinskrifter 759    51514457   
661          Upplands runinskrifter 763    54686058   
662          Upplands runinskrifter 764    54688368   
663          Upplands runinskrifter 765    54688642   
671          Upplands runinskrifter 775    54599487   
694          Upplands runinskrifter 803    54799252   
702          Upplands runinskrifter 813    54688586   
714          Upplands runinskrifter 828    54678528   
998   Upplands runinskrifter ATA6243/65    54791673   
1386    Södermanlands runinskrifter 377    56054071   

                                       translitterering  \
606   birn : lit : risa : s--- ...- : iftiʀ : sterbi...   
622   [...asr : auk : olifʀ : auk : uar:asi : li-......   
635   [(þ)(i)(l)stan : lit : ris... ... ...n : sun :...   
644   + ari + lit × ʀftia × usyrk · faþur + sin + --...   
657   ikib(i)rn : ak : þiʀ : bryþr : litu : risa : s...   
658   birynhiifʀ : ak : hrifnkʀ : ak : sik:ualti : u...   
661   bruni : ak : hulm:stin : litu : risa : istin :...   
662   brunk : ak : hulm:stin : litu : risa : istin :...   
663           -...k...-...-n : h...sl-...- : a-s : -...   
671   u[i]tarfʀ · lit · rsa · stin · linsa · ifi[ʀ ·...   
694   ulfr : lit : raesa : istaen siulfr : han : yif...   
702   [uiki...r · le- ...-isa · stain ...t · r... .....   
714   kakr × uk × a[k]un × litu × akua × sten × uk ×...   
998   ... ...(ʀ) : (b)---- ... ...--(t)en : suniʀ : ...   
1386               ... ...isa · sti- ... -t · su... ...   

                                          normalisering  \
606   Biorn let ræisa s[tæin þennsa] æftiʀ Styrbiorn...   
622   ... ok Olæifʀ ok Var-Asi()/Varr-Asi() le[tu] ....   
635   Þorstæinn() let ræis[a] ... ..., sun sinn goða...   
644   Ari let æftiʀ Osyrg, faður sinn. [Tið]kumi ris...   
657   Ingibiorn ok þæiʀ brøðr letu ræisa stæin þenna...   
658   Bryniulfʀ() ok Hræfningʀ() ok Sigvaldi letu ræ...   
661   Bruni ok Holmstæinn letu ræisa stæin þennsa æf...   
662   Bruni ok Holmstæinn letu ræisa stæin þennsa æf...   
663                                     ... ... ... ...   
671   Vidiarfʀ let ræisa stæin þennsa æftiʀ Asgæiʀ()...   
694        Ulfʀ let ræisa stæin, sialfʀ hann æftiʀ sik.   
702   Viki[ng]ʀ() le[t ræ]isa stæin [a]t ... ... sun...   
714   Kagʀ()/Gagʀ() ok Hakon letu haggva stæin ok br...   
998   ... [æfti]ʀ B[iorn]() [ok] [Þors]tæin(), syniʀ...   
1386             ... [ræ]isa stæi[n] ... [a]t su[n] ...   

                                            translation  Latitude  Longitude  \
606   Björn lät resa (denna sten) efter Styrbjörn, s...  59.49639   17.12510   
622   ... och Olev och '''uarasi''' läto ... denna s...  59.55498   17.14018   
635   Torsten() lät resa ..., sin gode son. Tidkume ...  59.59654   17.30669   
644   Are lät (resa stenen) efter Osyrg, sin fader ....  59.60033   17.12405   
657   Ingebjörn och bröderna med honom läto resa den...  59.63749   17.08005   
658   Brynjulv och Rävning () och Sigvalde läto resa...  59.63898   17.08096   
661   Brune och Holmsten läto resa stenen efter Gunn...  59.61380   17.10020   
662   Brune och Holmsten läto resa denna sten efter ...  59.61386   17.10017   
663                                                 NaN  59.61276   17.09235   
671   Vidjärv lät resa denna sten efter Åsger () och...  59.56718   17.02141   
694           Ulv lät resa stenen, han själv efter sig.  59.72419   17.13704   
702   Viking() lät resa stenen efter  ... son ... Gu...  59.68542   17.41468   
714   Gag och Håkon läto hugga stenen och göra bro e...  59.71556   17.44202   
998   … efter Björn () … och efter Torsten (), Fröst...  59.62408   17.09613   
1386                    ... resa sten ... efter son ...  59.41

In [29]:
# tegn stenar från Vg correspond to Olof Skötkonung late ruling dates https://sv.wikipedia.org/wiki/Olof_Sk%C3%B6tkonung
mask = df['translitterering'].str.contains('þikn', na=False, regex=False) #Öpir Tidkume þegn þikn
#print(df[mask])
X_pred = df_ML[mask]
X_pred = X_pred.fillna(0)
X_pred.columns = X_pred.columns.astype(str)
print(neigh.predict(X_pred)) 

[1023.5 1029.5 1029.5 1029.5 1023.5 1023.5 1023.5 1023.5 1029.5 1029.5]


In [30]:
# Ingvars sten is right after Ingvars tåget
mask = df['translitterering'].str.contains('ikuars', na=False, regex=False) #Öpir Tidkume þegn þikn
#print(df[mask])

X_pred = df_ML[mask]
X_pred = X_pred.fillna(0)
X_pred.columns = X_pred.columns.astype(str)
print(neigh.predict(X_pred)) 

[1057.]
